on: [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libglm-dev

      - name: make
        run: make

  build-debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libglm-dev

      - name: make debug
        run: make debug
